.TH HILBMETRIC 1L "March 02, 2014"
.ds Ps P\s-2OST\s+2S\s-2CRIPT\s+2
.ds Ts T\s-2RAN\s+2S\s-2CRIPT\s+2
.if t .ds Te T\\h'-0.1667m'\\v'0.20v'E\\v'-0.20v'\\h'-0.125m'X
.if n .ds Te TeX
.if t .ds La L\\h'-0.36m'\\v'-0.15v'\\s-2A\\s+2\\h'-0.15m'\\v'0.15v'T\\h'-0.1667m'\\v'0.20v'E\\v'-0.20v'\\h'-0.125m'X
.if n .ds La LaTeX
.ds Fl "F\s-2ranz\s+2\ L\s-2isp\s+2
.ds Ml "M\s-2ACLISP\s+2
.ds Cl "Common L\s-2isp\s+2
.ds Li "L\s-2isp\s+2
.ds Ky "GNU Common L\s-2isp\s+2
.ds Pr /usr
.ds Vr 5.31.3

.SH NAME
Hilbmetric \- Python program for the Hilbert projective metric
.SH SYNOPSIS
.B hilbmetric
[\fIoptions\fR]

.SH DESCRIPTION
Python program for the Hilbert projective metric.

.SH AUTHORS

K.I.A.Derouiche <kamel.derouiche@gmail.com>
.TP
.\"
